export type EntityDefinition = {
  canonicalType: string;
  domain: "electronics" | "grocery" | "beauty" | "general";
  headNouns: string[];
  categoryKeywords: string[];
  varieties?: string[];
  disqualifiers: string[];
  associatedTypes: string[];
};

export const BILINGUAL_EQUIVALENTS: Record<string, string[]> = {
  dhaniya: ["dhaniya", "dhania", "coriander", "cilantro"],
  coriander: ["coriander", "dhaniya", "dhania", "cilantro"],
  aloo: ["aloo", "alu", "potato", "potatoes"],
  potato: ["potato", "potatoes", "aloo", "alu"],
  pyaz: ["pyaz", "pyaaz", "kanda", "onion", "onions"],
  onion: ["onion", "onions", "pyaz", "pyaaz", "kanda"],
  tamatar: ["tamatar", "tomato", "tomatoes"],
  tomato: ["tomato", "tomatoes", "tamatar"],
  mirchi: ["mirchi", "mirch", "chilli", "chili", "chillies"],
  chilli: ["chilli", "chili", "mirchi", "mirch"],
  adrak: ["adrak", "ginger"],
  ginger: ["ginger", "adrak"],
  lehsun: ["lehsun", "lahsun", "garlic"],
  garlic: ["garlic", "lehsun", "lahsun"],
  nimbu: ["nimbu", "neembu", "lemon", "lime"],
  lemon: ["lemon", "lime", "nimbu"],
  palak: ["palak", "spinach"],
  spinach: ["spinach", "palak"],
  bhindi: ["bhindi", "okra", "lady finger", "ladies finger"],
  pudina: ["pudina", "mint"],
  mint: ["mint", "pudina"],
  methi: ["methi", "fenugreek"],
  gobhi: ["gobhi", "gobi", "cauliflower"],
  dahi: ["dahi", "curd", "yogurt", "yoghurt"],
  curd: ["curd", "dahi", "yogurt"],
  makhan: ["makhan", "butter"],
  paneer: ["paneer", "cottage cheese"],
  atta: ["atta", "wheat flour", "chakki atta"],
  chawal: ["chawal", "rice", "basmati"],
  dal: ["dal", "daal", "lentils", "pulses", "toor", "moong", "masoor", "chana", "urad"],
  namkeen: ["namkeen", "namkin", "bhujia", "sev", "mixture", "chivda", "farsan", "gathiya", "boondi"],
  biscuit: ["biscuit", "biscuits", "cookie", "cookies", "marie", "digestive", "bourbon", "krackjack", "monaco"],
  chai: ["chai", "tea"],
  doodh: ["doodh", "milk"]
};

export const ENTITY_ONTOLOGY: EntityDefinition[] = [
  {
    canonicalType: "potato",
    domain: "grocery",
    headNouns: ["potato", "potatoes", "aloo", "shakarkandi"],
    categoryKeywords: ["fresh vegetables", "vegetables", "root vegetables", "produce", "fruits & vegetables"],
    varieties: ["baby", "pahari", "new", "organic", "sweet", "red", "white", "chipsona", "jyoti"],
    disqualifiers: ["chips", "crisps", "wafer", "wafers", "bhujia", "namkeen", "biscuit", "cracker", "peeler", "masher", "slicer", "cutter", "noodles", "pasta", "papad", "paratha", "samosa", "tikki"],
    associatedTypes: ["onion", "tomato", "coriander", "ginger", "garlic", "green chilli", "curd", " cumin", "spices"]
  },
  {
    canonicalType: "coriander",
    domain: "grocery",
    headNouns: ["coriander", "dhaniya", "dhania", "cilantro"],
    categoryKeywords: ["fresh vegetables", "herbs", "leafy vegetables", "spices", "masalas", "fruits & vegetables"],
    varieties: ["fresh", "hara", "leaves", "bunch", "organic", "powder", "seeds", "whole", "sabut", "pisa"],
    disqualifiers: ["soap", "shampoo", "lotion", "perfume", "chutney jar", "container"],
    associatedTypes: ["green chilli", "mint", "ginger", "garlic", "lemon", "tomato", "potato", "onion", "curd"]
  },
  {
    canonicalType: "onion",
    domain: "grocery",
    headNouns: ["onion", "onions", "pyaz", "pyaaz", "kanda", "shallot"],
    categoryKeywords: ["fresh vegetables", "vegetables", "produce"],
    varieties: ["red", "white", "spring", "sambar", "baby", "organic", "peeled"],
    disqualifiers: ["hair oil", "shampoo", "conditioner", "serum", "scalp", "rings", "chips", "bhujia", "chopper", "slicer"],
    associatedTypes: ["potato", "tomato", "ginger", "garlic", "coriander", "green chilli", "lemon"]
  },
  {
    canonicalType: "tomato",
    domain: "grocery",
    headNouns: ["tomato", "tomatoes", "tamatar"],
    categoryKeywords: ["fresh vegetables", "vegetables", "produce"],
    varieties: ["hybrid", "desi", "local", "cherry", "organic", "plum"],
    disqualifiers: ["ketchup", "sauce", "soup", "chips", "tangy", "flavor", "flavour", "soap", "face"],
    associatedTypes: ["onion", "potato", "coriander", "green chilli", "ginger", "garlic", "cucumber"]
  },
  {
    canonicalType: "milk",
    domain: "grocery",
    headNouns: ["milk", "doodh", "toned milk", "full cream milk", "cow milk", "buffalo milk", "skimmed milk", "almond milk", "oat milk", "soy milk", "taaza", "gold milk"],
    categoryKeywords: ["dairy", "milk & cream", "dairy & breakfast", "dairy & bakery"],
    varieties: ["toned", "double toned", "full cream", "cow", "buffalo", "skimmed", "slim", "lactose free", "almond", "oat", "soy", "a2", "organic", "tetra", "pouch"],
    disqualifiers: ["makeup", "make up", "lip", "cheek", "blush", "primer", "cleanser", "lotion", "moisturizer", "serum", "face wash", "body wash", "soap", "shampoo", "conditioner", "biscuit", "cookies", "milk bikis", "dairy milk", "chocolate", "frother", "pan", "bottle"],
    associatedTypes: ["bread", "butter", "cereal", "cornflakes", "oats", "tea", "coffee", "biscuit", "eggs", "sugar"]
  },
  {
    canonicalType: "biscuit",
    domain: "grocery",
    headNouns: ["biscuit", "biscuits", "cookie", "cookies", "marie", "digestive", "bourbon", "oreo", "good day", "parle-g", "krackjack", "monaco", "hide & seek", "jim jam", "milk bikis", "nice time", "nutri choice", "nutrichoice", "dark fantasy"],
    categoryKeywords: ["biscuits", "cookies", "biscuits & cookies", "bakery & biscuits", "snacks"],
    varieties: ["cream", "marie", "digestive", "oats", "chocochip", "choco", "butter", "cashew", "almond", "salted", "sweet", "sugar free", "atta", "milk", "elaichi"],
    disqualifiers: ["dog biscuit", "pet food", "cat food", "biscuit cutter", "jar", "tin"],
    associatedTypes: ["tea", "coffee", "milk", "namkeen", "rusk", "cake", "chips"]
  },
  {
    canonicalType: "namkeen",
    domain: "grocery",
    headNouns: ["namkeen", "bhujia", "sev", "mixture", "chivda", "farsan", "moong dal", "chana dal", "khatta meetha", "navratan", "boondi", "gathiya", "kurkure", "chakli", "murukku", "mathri", "peanut", "masala peanuts", "bhel"],
    categoryKeywords: ["namkeen", "munchies", "chips & namkeen", "savory snacks", "indian snacks", "snacks & branded foods"],
    varieties: ["aloo bhujia", "bikaneri bhujia", "ratlami sev", "khatta meetha", "navratan", "moong dal", "hing", "pudina", "spicy", "roasted", "diet"],
    disqualifiers: ["sweet", "gulab jamun", "rasgulla", "soan papdi", "container", "box"],
    associatedTypes: ["tea", "biscuit", "cold drink", "cola", "juice", "chips"]
  },
  {
    canonicalType: "chips",
    domain: "grocery",
    headNouns: ["chips", "crisps", "wafers", "potato chips", "banana chips", "tortilla chips", "nachos", "pringles", "lays", "lay's", "bingo", "uncle chipps", "too yumm"],
    categoryKeywords: ["chips", "crisps", "munchies", "chips & namkeen", "snacks"],
    varieties: ["salted", "masala", "magic masala", "cream & onion", "sour cream", "tomato", "peri peri", "cheese", "banana", "baked"],
    disqualifiers: ["chocolate chips", "choco chips", "wood chips", "poker chips", "ic chip"],
    associatedTypes: ["cold drink", "cola", "dip", "salsa", "namkeen", "biscuit"]
  },
  {
    canonicalType: "bread",
    domain: "grocery",
    headNouns: ["bread", "loaf", "pav", "bun", "kulcha", "bagel", "croissant", "rusk"],
    categoryKeywords: ["bakery", "bread & pav", "dairy & bakery"],
    varieties: ["brown", "white", "multigrain", "whole wheat", "atta", "milk", "sandwich", "garlic"],
    disqualifiers: ["bread maker", "toaster", "bread box", "bread knife", "board", "crumbs"],
    associatedTypes: ["butter", "milk", "jam", "peanut butter", "cheese", "eggs"]
  },
  {
    canonicalType: "butter",
    domain: "grocery",
    headNouns: ["butter", "makhan", "table butter"],
    categoryKeywords: ["dairy", "butter & cream", "dairy & bakery"],
    varieties: ["salted", "unsalted", "white", "garlic", "herb", "peanut", "almond"],
    disqualifiers: ["body butter", "lip butter", "shea butter", "cocoa butter", "hair", "lotion", "cream blush", "makeup", "butter knife", "butter dish", "cookies", "biscuit", "murukku", "chakli"],
    associatedTypes: ["bread", "pav", "milk", "jam", "cheese", "paratha"]
  },
  {
    canonicalType: "curd",
    domain: "grocery",
    headNouns: ["curd", "dahi", "yogurt", "yoghurt", "mishti doi", "greek yogurt"],
    categoryKeywords: ["dairy", "curd & yogurt", "dairy & bakery"],
    varieties: ["toned", "thick", "greek", "flavored", "strawberry", "blueberry", "mango", "probiotic", "pouch", "cup"],
    disqualifiers: ["hair", "face", "skin", "soap", "maker"],
    associatedTypes: ["potato", "paratha", "rice", "coriander", "milk", "paneer"]
  },
  {
    canonicalType: "laptop",
    domain: "electronics",
    headNouns: ["laptop", "macbook", "notebook", "ultrabook", "chromebook", "thinkpad", "ideapad", "legion", "pavilion", "envy", "omen", "inspiron", "xps", "latitude", "alienware", "vivobook", "zenbook", "rog", "tuf", "aspire", "nitro", "predator", "swift"],
    categoryKeywords: ["traditional laptops", "2 in 1 laptops", "laptops", "notebooks"],
    varieties: ["gaming", "air", "pro", "2-in-1", "convertible", "business"],
    disqualifiers: ["smartphone", "android smartphone", "iphone", "tablet", "galaxy tab", "ipad", "wrist rest", "palm support", "mouse pad", "laptop bag", "laptop sleeve", "laptop stand", "cooling pad", "screen protector", "keyboard cover", "webcam cover", "skin", "sticker", "charger for", "case for", "cover for"],
    associatedTypes: ["laptop bag", "laptop sleeve", "backpack", "wireless mouse", "usb hub", "laptop stand", "cooling pad", "wrist rest", "docking station"]
  },
  {
    canonicalType: "smartphone",
    domain: "electronics",
    headNouns: ["smartphone", "iphone", "mobile phone", "cell phone", "android phone", "ai phone"],
    categoryKeywords: ["smartphones", "mobile phones", "cell phones"],
    varieties: ["5g", "4g", "pro", "ultra", "plus", "max", "fold", "flip"],
    disqualifiers: ["tablet", "galaxy tab", "ipad", "laptop", "macbook", "smartwatch", "watch", "phone case", "back cover", "screen protector", "tempered glass", "charger for", "cable for", "holder", "mount", "earbuds"],
    associatedTypes: ["phone case", "back cover", "screen protector", "tempered glass", "fast charger", "usb cable", "power bank", "earbuds"]
  },
  {
    canonicalType: "tablet",
    domain: "electronics",
    headNouns: ["tablet", "ipad", "galaxy tab", "surface pro"],
    categoryKeywords: ["tablets", "tablet pcs"],
    varieties: ["wifi", "5g", "lte", "pro", "air", "mini"],
    disqualifiers: ["smartphone", "laptop", "tablet case", "ipad case", "screen protector", "stand for", "holder for", "dishwash tablet", "medicine"],
    associatedTypes: ["tablet case", "screen protector", "stylus", "keyboard cover", "usb c charger"]
  },
  {
    canonicalType: "mouse",
    domain: "electronics",
    headNouns: ["mouse", "wireless mouse", "gaming mouse", "bluetooth mouse", "optical mouse"],
    categoryKeywords: ["mice", "computer mice"],
    varieties: ["wireless", "bluetooth", "wired", "gaming", "ergonomic", "vertical", "rechargeable"],
    disqualifiers: ["mouse pad", "mousepad", "wrist rest", "palm support", "case for", "pouch for", "mouse trap"],
    associatedTypes: ["mouse pad", "wrist rest", "keyboard", "usb hub"]
  }
];

export const QUERY_SYNONYMS: Record<string, string> = {
  mobile: "smartphone",
  phone: "smartphone",
  cellphone: "smartphone",
  iphone: "smartphone",
  macbook: "laptop",
  notebook: "laptop",
  ultrabook: "laptop",
  chromebook: "laptop",
  ipad: "tablet",
  dhaniya: "coriander",
  dhania: "coriander",
  cilantro: "coriander",
  aloo: "potato",
  alu: "potato",
  potatoes: "potato",
  pyaz: "onion",
  pyaaz: "onion",
  kanda: "onion",
  onions: "onion",
  tamatar: "tomato",
  tomatoes: "tomato",
  doodh: "milk",
  dahi: "curd",
  yogurt: "curd",
  makhan: "butter",
  biscuits: "biscuit",
  cookies: "biscuit",
  cookie: "biscuit",
  bhujia: "namkeen",
  sev: "namkeen",
  mixture: "namkeen",
  chivda: "namkeen",
  farsan: "namkeen",
  wafers: "chips",
  crisps: "chips"
};

export const MODIFIER_LEXICON: Record<string, string[]> = {
  gaming: ["gaming", "rtx", "gtx", "geforce", "radeon rx", "rog", "tuf", "legion", "omen", "nitro", "predator", "alienware", "katana", "razer", "144hz", "165hz", "240hz"],
  wireless: ["wireless", "bluetooth", "2.4ghz", "cordless"],
  organic: ["organic", "jaivik", "natural", "chemical free", "pesticide free"],
  fresh: ["fresh", "hara", "taza", "taaza", "farm fresh", "green"],
  hara: ["hara", "fresh", "green", "leaves", "bunch"],
  powder: ["powder", "pisa", "ground", "masala"],
  whole: ["whole", "sabut", "seeds"],
  baby: ["baby", "chota", "small", "mini", "sambar"],
  pahari: ["pahari", "pahadi", "hill", "nainital"],
  new: ["new", "naya", "fresh harvest"],
  sweet: ["sweet", "shakarkandi", "meetha"],
  toned: ["toned", "taaza", "double toned", "low fat"],
  full_cream: ["full cream", "gold", "rich", "malai"],
  salted: ["salted", "namkeen", "classic salted", "magic masala"],
  digestive: ["digestive", "high fibre", "fiber", "multigrain", "oats"],
  marie: ["marie", "marie gold", "tea time"],
  cream: ["cream", "bourbon", "oreo", "jim jam", "choco", "vanilla", "strawberry"]
};

export const COMMON_TYPOS: Record<string, string> = {
  lapotp: "laptop",
  laptp: "laptop",
  latop: "laptop",
  lpatop: "laptop",
  laptops: "laptop",
  macbok: "macbook",
  mcbook: "macbook",
  macboook: "macbook",
  mackbook: "macbook",
  samsng: "samsung",
  samung: "samsung",
  smsung: "samsung",
  samsun: "samsung",
  iphon: "iphone",
  ipone: "iphone",
  iphne: "iphone",
  appl: "apple",
  aple: "apple",
  amool: "amul",
  amull: "amul",
  mlik: "milk",
  mikl: "milk",
  wirless: "wireless",
  wireles: "wireless",
  mous: "mouse",
  phne: "phone",
  phon: "phone",
  gamng: "gaming",
  gming: "gaming",
  dhania: "dhaniya",
  daniya: "dhaniya",
  dhniya: "dhaniya",
  coriender: "coriander",
  corriander: "coriander",
  patato: "potato",
  pototo: "potato",
  pottato: "potato",
  alloo: "aloo",
  biscut: "biscuit",
  biskit: "biscuit",
  bisquit: "biscuit",
  biscuts: "biscuit",
  namkin: "namkeen",
  numkeen: "namkeen",
  bhujiya: "bhujia",
  bhujya: "bhujia"
};

export const KNOWN_BRANDS = [
  "samsung",
  "apple",
  "amul",
  "mother dairy",
  "nandini",
  "almarai",
  "nestle",
  "britannia",
  "parle",
  "sunfeast",
  "unibic",
  "mcVitie's",
  "mcvities",
  "oreo",
  "haldiram",
  "haldiram's",
  "haldirams",
  "bikaji",
  "balaji",
  "kurkure",
  "lays",
  "lay's",
  "bingo",
  "pringles",
  "too yumm",
  "aashirvaad",
  "fortune",
  "tata sampann",
  "tata tea",
  "red label",
  "taj mahal",
  "bru",
  "nescafe",
  "mdh",
  "everest",
  "catch",
  "kelloggs",
  "kellogg's",
  "quaker",
  "bagrrys",
  "fresho",
  "relifresh",
  "lenovo",
  "hp",
  "dell",
  "asus",
  "acer",
  "msi",
  "sony",
  "lg",
  "logitech",
  "oneplus",
  "xiaomi",
  "huawei",
  "anker"
];